<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="3.1.1" />
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.101.1" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.100.3" />
        <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.101.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="Slugify.Core" Version="5.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Toxon.Photography.Data\Toxon.Photography.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\**\*" />
        <Content Include="Assets\**\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    
</Project>
