AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  HttpApi:
    CorsConfiguration:
      AllowMethods: 
        - "*"
      AllowHeaders: 
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      AllowOrigins: 
        - "*"
    Auth:
      EnableIamAuthorizer: true
  Function:
    Timeout: 100
    Environment:
      Variables:
        PHOTOGRAPH_TABLE: !Ref PhotographyTable
        STORY_TABLE: !Ref StoriesTable
        IMAGE_BUCKET: !Ref ImageBucket
        SITE_BUCKET: !Ref SiteBucket

Parameters: 
  SiteAcmCertificateArn:
    Type: String
  SiteAliases:
    Type: CommaDelimitedList
  CloudFrontImageBaseUrl:
    Type: String
  CloudFrontImageKeyPairId:
    Type: String
  CloudFrontImageTrustedKeyGroupId:
    Type: String
  CloudFrontPrivateKeySsmPath:
    Type: String

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./src/Toxon.Photography/
      Handler: Toxon.Photography
      Runtime: dotnet8
      MemorySize: 10240
      Environment:
        Variables:
          SITE_GENERATOR_LAMBDA: !Ref SiteGeneratorFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PhotographyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref StoriesTable
        - S3CrudPolicy:
            BucketName: !Ref ImageBucket
        - LambdaInvokePolicy:
            FunctionName: !Ref SiteGeneratorFunction
        - EventBridgePutEventsPolicy:
            EventBusName: "*"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-lite-v1:0"
                - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-pro-v1:0"
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: "2.0"
            Path: /{proxy+}
            Method: ANY
            Auth:
              Authorizer: AWS_IAM
        CorsProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: "2.0"
            Path: /{proxy+}
            Method: OPTIONS

  SiteGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Toxon.Photography.Generation
      Handler: Toxon.Photography.Generation::Toxon.Photography.Generation.SiteGeneratorLambda::FunctionHandlerAsync
      Runtime: dotnet8
      MemorySize: 1024
      Environment:
        Variables:
          CLOUDFRONT_IMAGE_BASE_URL: !Ref CloudFrontImageBaseUrl
          CLOUDFRONT_IMAGE_KEY_PAIR_ID: !Ref CloudFrontImageKeyPairId
          CLOUDFRONT_PRIVATE_KEY_SSM_PATH: !Ref CloudFrontPrivateKeySsmPath
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PhotographyTable
        - DynamoDBReadPolicy:
            TableName: !Ref StoriesTable
        - S3ReadPolicy:
            BucketName: !Ref ImageBucket
        - S3CrudPolicy:
            BucketName: !Ref SiteBucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${CloudFrontPrivateKeySsmPath}"
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 day)"
            OmitName: true

  SiteCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        HttpVersion: http2and3
        Aliases: !Ref SiteAliases
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: site-s3
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: "thumbnail/*"
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            TargetOriginId: image-s3
            ViewerProtocolPolicy: redirect-to-https
            TrustedKeyGroups:
              - !Ref CloudFrontImageTrustedKeyGroupId

        Origins:
          - Id: site-s3
            DomainName: !GetAtt [SiteBucket, RegionalDomainName]
            OriginAccessControlId: !Ref SiteBucketCloudFrontOac
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: image-s3
            DomainName: !GetAtt [ImageBucket, RegionalDomainName]
            OriginAccessControlId: !Ref ImageBucketCloudFrontOac
            S3OriginConfig:
              OriginAccessIdentity: ""

        ViewerCertificate: 
          AcmCertificateArn: !Ref SiteAcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  SiteBucketCloudFrontOac:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Join ["-", ["photography-site-oac", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
        Description: Access control for site bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ImageBucketCloudFrontOac:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Join ["-", ["photography-images-oac", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
        Description: Access control for image bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  PhotographyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Join ["-", ["photography", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
        
  StoriesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Join ["-", ["photography-stories", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join ["-", ["photography-images", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration: 
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - ETag
              - Date
            MaxAge: 3600
  SiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join ["-", ["photography-site", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref SiteBucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Join ["", ["arn:aws:s3:::", !Ref SiteBucket, "/*"]]
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${SiteCloudfront}"

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Join ["", ["arn:aws:s3:::", !Ref ImageBucket, "/*"]]
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${SiteCloudfront}"
            
  # cognito for the admin panel
  AdminUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join ["-", ["photography-admin", !Select ["0", !Split ["-", !Select ["2", !Split ["/", !Ref AWS::StackId ]]]]]]
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AliasAttributes: [email]
      AutoVerifiedAttributes: [email]
  AdminUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Join [ "-", [ "photography-admin", !Select [ "0", !Split [ "-", !Select [ "2", !Split [ "/", !Ref AWS::StackId ] ] ] ] ] ]
      UserPoolId: !Ref AdminUserPool
      GenerateSecret: false
  AdminIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Join [ "-", [ "photography-admin", !Select [ "0", !Split [ "-", !Select [ "2", !Split [ "/", !Ref AWS::StackId ] ] ] ] ] ]
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref AdminUserPoolClient
          ProviderName: !GetAtt [AdminUserPool, ProviderName]
  AdminIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties: 
      IdentityPoolId: !Ref AdminIdentityPool
      Roles:
        authenticated: !GetAtt [AdminRole, Arn]
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ "photography-admin-cognito", !Select [ "0", !Split [ "-", !Select [ "2", !Split [ "/", !Ref AWS::StackId ] ] ] ] ] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref AdminIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
            Action:
              - "sts:AssumeRoleWithWebIdentity"
      Policies: 
        - PolicyName: AdminPanelAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource:
                  - !Sub "${ImageBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: 
                  - !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessHttpApi}/*"
  
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  ImageBucket:
    Description: "Image bucket name"
    Value: !Ref ImageBucket
  SiteEndpoint:
    Description: "Generated site cloudfront URL"
    Value: !Join ["", ["https://", !GetAtt [SiteCloudfront, DomainName]]]
  AdminUserPoolId:
    Description: "Id of the user pool for authenticating with the admin panel"
    Value: !Ref AdminUserPool
  AdminUserPoolClientId:
    Description: "Id of the user pool client for authenticating with the admin panel"
    Value: !Ref AdminUserPoolClient
  AdminIdentityPoolId:
    Description: "Id of the identity pool for authenticating with the admin panel"
    Value: !Ref AdminIdentityPool
