create-photograph:
  handler: Toxon.Photography::Toxon.Photography.CreatePhotographFunction::Handle
  events:
    - http:
        path: photograph
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
list-photographs:
  handler: Toxon.Photography::Toxon.Photography.ListPhotographsFunction::Handle
  events:
    - http:
        path: photograph
        method: get
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer

# image processors
thumbnail-processor:
  handler: Toxon.Photography::Toxon.Photography.ThumbnailProcessorFunction::Handle
  events:
    - sns:
        arn:
          Ref: ImageProcessorTopic
        # ideally this would be `Fn::GetAtt: [ImageProcessorTopic, TopicName]`
        # but there seems to be bug where topicName must be a string if arn is ref
        topicName: ${self:custom.imageProcessorTopicName}
