- Effect: Allow
  Action:
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource:
    Fn::GetAtt: [PhotographTable, Arn]
- Effect: Allow
  Action:
    - s3:GetObject
    - s3:PutObject
    - s3:DeleteObject
  Resource:
    Fn::Join:
      - "/"
      - - ${self:custom.imageBucketArn}
        - "*"
- Effect: Allow
  Action:
    - s3:PutObject
    - s3:DeleteObject
  Resource:
    Fn::Join:
      - "/"
      - - ${self:custom.siteBucketArn}
        - "*"
- Effect: Allow
  Action:
    - sns:Publish
  Resource:
    Ref: ImageProcessorTopic
# This is only actually required for the site-generator function
- Effect: Allow
  Action:
    - ssm:GetParameter
    - ssm:GetParameters
  Resource:
    - "Fn::Join":
        - ":"
        - - "arn:aws:ssm"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "parameter/${self:service}-${self:provider.stage}-SiteGeneratorSigningUser-AccessKey"
    - "Fn::Join":
        - ":"
        - - "arn:aws:ssm"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "parameter/${self:service}-${self:provider.stage}-SiteGeneratorSigningUser-SecretKey"
# This is required by the ECS trigger
- Effect: Allow
  Action:
    - ecs:RunTask
    - iam:PassRole
  Resource:
    - Ref: ThumbnailProcessorTask
    - Fn::GetAtt: [ThumbnailProcessorExecutionRole, Arn]
    - Fn::GetAtt: [ThumbnailProcessorTaskRole, Arn]
