Resources:
  UserAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${self:provider.stage}-UserAccessRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud":
                  Ref: IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-UserAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource:
                  Fn::Join:
                    - "/"
                    - - ${self:custom.imageBucketArn}
                      - "*"

  SiteGeneratorSigningUser:
    Type: AWS::IAM::User
    Properties:
      UserName: ${self:service}-${self:provider.stage}-SiteGeneratorSigningUser
  SiteGeneratorSigningPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ${self:service}-${self:provider.stage}-SiteGeneratorSigningPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              Fn::Join:
                - "/"
                - - ${self:custom.imageBucketArn}
                  - "*"
      Users:
        - Ref: SiteGeneratorSigningUser
