Resources:
  # ECS
  ThumbnailProcessorRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: toxon/${self:service}-${self:provider.stage}-thumbnailprocessor

  ThumbnailProcessorTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: ${self:service}-${self:provider.stage}-thumbnailprocessor
          Image:
            Fn::Join:
              - ""
              - - Ref: AWS::AccountId
                - ".dkr.ecr."
                - Ref: AWS::Region
                - ".amazonaws.com/"
                - Ref: ThumbnailProcessorRepository
                - ":latest"
          Cpu: 512
          Memory: 4096
          Environment:
            - Name: PHOTOGRAPH_TABLE
              Value: ${self:provider.environment.PHOTOGRAPH_TABLE}
            - Name: IMAGE_BUCKET
              Value: ${self:provider.environment.IMAGE_BUCKET}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: ThumbnailProcessorTaskLogsGroup
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: ecs

      ExecutionRoleArn:
        Ref: ThumbnailProcessorExecutionRole
      TaskRoleArn:
        Ref: ThumbnailProcessorTaskRole

      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 4GB
      NetworkMode: awsvpc

  ThumbnailProcessorCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ${self:service}-${self:provider.stage}-thumbnailprocessor

  # CloudWatch
  ThumbnailProcessorTaskLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/ecs/"
            - Ref: AWS::StackName
            - "/ThumbnailProcessorTask"
      RetentionInDays: 7

  # IAM
  ThumbnailProcessorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-ThumbnailProcessorExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvent
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"

  ThumbnailProcessorTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-ThumbnailProcessorTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  Fn::Join:
                    - "/"
                    - - ${self:custom.imageBucketArn}
                      - "*"
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource: ${self:custom.photographTableArn}

  # VPC
  ThumbnailProcessorVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
  ThumbnailProcessorSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ThumbnailProcessorVpc
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
  ThumbnailProcessorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: ThumbnailProcessorVpc
      GroupDescription: Default ThumbnailProcessor security group
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ThumbnailProcessorRoutes:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: ThumbnailProcessorVpc
  ThumbnailProcessorRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: ThumbnailProcessorRoutes
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: ThumbnailProcessorInternetGateway
  ThumbnailProcessorInternetGateway:
    Type: AWS::EC2::InternetGateway
  ThumbnailProcessorAttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: ThumbnailProcessorVpc
      InternetGatewayId:
        Ref: ThumbnailProcessorInternetGateway
  ThumbnailProcessorAttachSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: ThumbnailProcessorSubnet
      RouteTableId:
        Ref: ThumbnailProcessorRoutes
